name: e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: my-secret
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Install circom
        uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/iden3/circom/releases/download/v2.2.1/circom-linux-amd64
          name: circom
          version: 2.2.2

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install snarkjs
        run: |
          npm install -g snarkjs

      - name: Checkout Zeto
        uses: actions/checkout@v4
        with:
          path: zeto
          fetch-depth: 0

      - name: Setup temp dir for the artifacts
        run: |
          mkdir -p ${{ runner.temp }}/zeto-artifacts

      - name: Build circuits
        env:
          CIRCUITS_ROOT: ${{ runner.temp }}/zeto-artifacts
          PROVING_KEYS_ROOT: ${{ runner.temp }}/zeto-artifacts
          PTAU_DOWNLOAD_PATH: ${{ runner.temp }}/zeto-artifacts
        working-directory: zeto/zkp/circuits
        run: |
          npm install
          npm run gen
          if [[ -n $(git status --porcelain) ]]; then
            echo "Error: 'npm run gen' caused changes in the repository, please run the command locally to commit in all changes."
            git status --porcelain
            echo "Detailed changes:"
            git diff
            exit 1
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run golang e2e tests
        env:
          PROVING_KEYS_ROOT: ${{ runner.temp }}/zeto-artifacts
          CIRCUITS_ROOT: ${{ runner.temp }}/zeto-artifacts
        working-directory: zeto/go-sdk
        run: |
          make e2e

      - name: Run js e2e tests
        env:
          PROVING_KEYS_ROOT: ${{ runner.temp }}/zeto-artifacts
          CIRCUITS_ROOT: ${{ runner.temp }}/zeto-artifacts
        working-directory: zeto/zkp/js
        run: |
          npm install
          npm run test:e2e

      - name: Run Zeto Tokens hardhat tests as upgradeable contracts
        env:
          PROVING_KEYS_ROOT: ${{ runner.temp }}/zeto-artifacts
          CIRCUITS_ROOT: ${{ runner.temp }}/zeto-artifacts
        working-directory: zeto/solidity
        run: |
          npm install
          npm t

      - name: Run Zeto Tokens hardhat tests as cloned contracts
        env:
          USE_FACTORY: true
          PROVING_KEYS_ROOT: ${{ runner.temp }}/zeto-artifacts
          CIRCUITS_ROOT: ${{ runner.temp }}/zeto-artifacts
        working-directory: zeto/solidity
        run: |
          npm install
          npm t
